<?php
echo "
<div id='cuerpo-centro'>
<h1>DIETAS</h1>
<center>
		<p>La Orden EHA/3771/2005 de dis de diciembre establece las remuneraciones en concepto de dietas y kilometraje:</p>
	
			<table width='443' border='5' id='inaddi_clasetable'>
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Manutenci&#243n sin pecnoctar</td>
					<td id='inaddi_td'>18,70&#8364</td>
				</tr>
		
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Manutenci&#243n pernoctando</td>
					<td id='inaddi_td'>37,40&#8364</td>
				</tr id=tr>
		
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Alojamiento</td>
					<td id='inaddi_td'>65,97&#8364</td>
				</tr>
		
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Dieta completa (manutenci&#243n + alojamiento)</td>
					<td id='inaddi_td'>103,37&#8364</td>
				</tr>
		
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Veh&#237culo propio (por cada Km.)</td>
					<td id='inaddi_td'>0,19&#8364</td>
				</tr>
		
				<tr id=inaddi_tr>
					<td id='inaddi_td'>Motocicleta propia (por cada Km.)</td>
					<td id='inaddi_td'>0,078&#8364</td>
				</tr>
			</table>
</center>			
</div>";
?>
