<div id='cuerpo-centro'>
  <h1>AMPA</H1>
  <hr />
  <div>
Para hacer uso de una taquilla <b>durante un curso completo</b> debes seguir los siguientes pasos:
<ul>
<li>Ingresar 20€ en la cuenta que el AMPA tiene abierta en Bankia: 2038 - 1804 - 60 - 6000047887.</li>
<li>Entregar el justificante de ingreso en Jefatura cualquier día o los jueves de 18:00 a 19:00 en la sala de ordenadores del salón de actos</li>
</ul>
  </div>
</div>
