<div id='cuerpo-centro'>
  <!--div class="imagenes_enlaces_importantes">
    <a href='Inicio/Inicio/Puertas_abiertas_2016.pdf'>
      <img src='Inicio/Inicio/images/Puertas_abiertas_2016.jpg' />
    </a>
  </div-->
  <div class="imagenes_enlaces">
    <a href='http://www.educa2.madrid.org/web/tiernogalvan'>
       <img src='Inicio/Inicio/images/tierno.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='http://www.educa2.madrid.org/web/educamadrid/principal/files/e5ba4081-1cc7-4c01-aef2-78afd533a57d/Calendario_examenes_libres.pdf?t=1460485310351'>
       <img src='Inicio/Inicio/images/Examenes_libres.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='Inicio/Secretaria/Libros_texto.pdf'>
      <img src='Inicio/Inicio/images/Libros_texto.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='Inicio/Inicio/Programa_semana_cultural_2016.pdf'>
       <img src='Inicio/Inicio/images/Semana_cultural.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='Inicio/Inicio/Propaganda_14_15_ESO.pdf'>
       <img src='Inicio/Inicio/images/Informacion.jpg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='http://www.educa2.madrid.org/web/tiernogalvan/erasmus'>
       <img src='Inicio/Inicio/images/Erasmus.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='http://www.madrid.org/cs/Satellite?idConsejeria=1109266187254&idListConsj=1109265444710&c=CM_InfPractica_FA&pagename=ComunidadMadrid%2FEstructura&sm=1109266100977&cid=1142649238708&language=es&idOrganismo=1142359974952'>
       <img src='Inicio/Inicio/images/Calendario_escolar.jpeg' />
    </a>
  </div>
  <div class="imagenes_enlaces">
    <a href='http://www.educa2.madrid.org/web/educamadrid/principal/files/116e8fe1-4d8a-42e6-90b9-70ec9751cf7f/Tutorial_educamadrid.pdf?t=1452189906268'>
       <img src='Inicio/Inicio/images/Crea_web.jpeg' />
    </a>
  </div>
  <!---div class="imagenes_enlaces">
    <a href='http://www.educa2.madrid.org/web/tiernogalvan'>
       <img src='Inicio/Inicio/images/tierno.jpeg' />
    </a>
  </div-->
<!--ul class='lista_grande'>
  <p>Y además ...</p>
  <li><a href='http://www.educa2.madrid.org/web/tiernogalvan'>Web oficial en Educamadrid</a></li>
  <li><a href='Alumnos/Inicio/Premio.png'>Alumno premiado</a></li>
  <li><a href='Inicio/Inicio/examenes_sep.pdf'>Exámenes de Septiembre ESO y BACH</a></li>
  <li><a href='Inicio/Inicio/examenes_sep_fp.pdf'>Exámenes de Septiembre FP 2015</a></li>
  
</ul-->
</div>

