<div id='cuerpo-centro'>
<h1>HOME</h1>
<hr size='5' width='600' color='white' />
<ul class='lista_grande'>
  <li><a href='Inicio/Inicio/Programa_semana_cultural_2016.pdf'>Cultural week</a></li>
  <li><a href='Inicio/Inicio/Carta_Directora.pdf'>Open day</a></li>
  <li><a href='Inicio/Inicio/Propaganda_14_15_ESO.pdf'>Information for the ESO</a></li>
  <br />
  <li><a href='Alumnos/Inicio/Premio.png'>Awarded student</a></li>
  <li><a href='http://www.educa2.madrid.org/web/educamadrid/principal/files/116e8fe1-4d8a-42e6-90b9-70ec9751cf7f/Tutorial_educamadrid.pdf?t=1452189906268'>Tutorial to make your Web</a></li>
  <li><a href='Inicio/Secretaria/Libros_texto.pdf'>Textbooks</a></li>
  <!--li><a href='Inicio/Inicio/Examenes_septiembre_eso.pdf'>September Exams ESO and Bachillerato</a></li-->
  <!--li><a href='Inicio/Inicio/Examenes_septiembre_fp.pdf'>September Exams F.P.</a></li-->
  <!--li><a href='Inicio/Inicio/Calendario_septiembre.pdf'>September Schedule</a></li-->
  <!--li><a href='Inicio/Inicio/Sesiones_eval.pdf'>Evaluation Sessions</a></li-->
  <li><a href='http://www.educa2.madrid.org/web/tiernogalvan/erasmus'>Erasmus Project</a></li>
  <li><a href='http://www.madrid.org/cs/Satellite?idConsejeria=1109266187254&idListConsj=1109265444710&c=CM_InfPractica_FA&pagename=ComunidadMadrid%2FEstructura&sm=1109266100977&cid=1142649238708&language=es&idOrganismo=1142359974952'>School General Calendar</a></li>
  <li><a href='http://www.educa2.madrid.org/web/educamadrid/principal/files/ebdc947b-95ca-43da-82e9-cb55fc579939/OrdenCalendarioEscolar20132014.pdf?t=1373041112064'>Order 2182/2013: School Calendar 2013</a></li>
  <br />
<p>OTRAS WEB DEL CENTRO</p>
  <li><a href='http://www.educa2.madrid.org/web/tiernogalvan'>Oficial Website at Educamadrid</a>
  <li><a href='http://80.38.194.78'>Former Intranet</a></li>
</ul>
</div>

