<a href="index.php?dep=inf">Atr&aacute;s</a>
<h1>Ciclo Formativo Administraci&oacute;n de Sistemas Inform&aacute;ticos en Red</h1>
<script type="text/javascript">
 var cambiar = {
    accion:  function(hide, show){ this.ocultar(hide); this.mostrar(show); },
    ocultar: function(num){ document.getElementById("div"+num).style['display'] = "none"; },
    mostrar: function(num){ document.getElementById("div"+num).style['display'] = "block"; }
 };
</script>

<div style="text-align:left; padding:10px;">
<span class="indicepag">
<h2>Informaci&oacute;n de interes</h2>
 El alumno al terminar ser&aacute; capaz de:
<ul>
<li>Administrar sistemas operativos de servidor, instalando y configurando el software, en condiciones de calidad para asegurar el funcionamiento del sistema.</li>
<li>Administrar servicios de red (web, mensajer&iacute;a electr&oacute;nica y transferencia de archivos, entre otros) instalando y configurando el software, en condiciones de calidad.</li>
<li>Implantar y gestionar bases de datos instalando y administrando el software de gesti&oacute;n en condiciones de calidad, seg&uacute;n las caracter&iacute;sticas de la explotaci&oacute;n.</li>
<li>Evaluar el rendimiento de los dispositivos hardware identificando posibilidades de mejoras seg&uacute;n las necesidades de funcionamiento.</li>
<li>Determinar la infraestructura de redes telem&aacute;ticas elaborando esquemas y seleccionando equipos y elementos.</li>
<li>Integrar equipos de comunicaciones en infraestructuras de redes telem&aacute;ticas, determinando la configuraci&oacute;n para asegurar su conectividad.</li>
<li>Administrar usuarios de acuerdo a las especificaciones de explotaci&oacute;n para garantizar los accesos y la disponibilidad de los recursos del sistema.</li>
<li>Diagnosticar las disfunciones del sistema y adoptar las medidas correctivas para restablecer su funcionalidad.</li>
<li>Gestionar y/o realizar el mantenimiento de los recursos de su &aacute;rea (programando y verificando su cumplimiento), en funci&oacute;n de las cargas de trabajo y el plan de mantenimiento.</li>
</ul>
Puestos de trabajo que pueden desempe&ntilde;ar:
 <ul>
  <li>T&eacute;cnico en administraci&oacute;n de sistemas</li>
  <li>Responsable de inform&aacute;tica.</li>
  <li>T&eacute;cnico en servicios de Internet. </li>
  <li>T&eacute;cnico en servicios de mensajer&iacute;a electr&oacute;nica. </li>
  <li>Personal de apoyo y soporte t&eacute;cnico. </li>
  <li>T&eacute;cnico en teleasistencia. </li>
  <li>T&eacute;cnico en administraci&oacute;n de base de datos. </li>
  <li>T&eacute;cnico de redes. </li>
  <li>Supervisor de sistemas. </li>
  <li>T&eacute;cnico en servicios de comunicaciones. </li>
  <li>T&eacute;cnico en entornos web.</li>
 
					</ul>
<h2>Modulos/Asignaturas</h2>
<button onclick="cambiar.accion(2,1)" class="boton_cambio primercurso">Primer Curso</button>
<button onclick="cambiar.accion(1,2)" class="boton_cambio segundocurso">Segundo curso</button>
  <div class="divTable" id="div1">
             <div class="headRow">
                <div class="divCell" align="center">Asignatura</div>
                <div  class="divCell">Informaci&oacute;n</div>
             </div>
            <div class="divRow">
                <div class="divCell">Planificaci&oacute;n y administraci&oacute;n de redes.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=17">+info</a></div>
					</div>
				</div>
            </div>
            <div class="divRow">
                 <div class="divCell">Implantaci&oacute;n de sistemas operativos. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=12">+info</a></div>
					</div>
				</div>
           </div>
            <div class="divRow">
               <div class="divCell">Fundamentos de hardware</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=21">+info</a></div>
					</div>
				</div>
           </div>
		   <div class="divRow">
               <div class="divCell">Gesti&oacute;n de bases de datos.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=25">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Lenguajes de marcas y sistemas de gesti&oacute;n de informaci&oacute;n. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=29">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Formaci&oacute;n y orientaci&oacute;n laboral. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=56">+info</a></div>
					</div>
				</div>
           </div>

      </div>
  <div class="divTable" id="div2"  style="display: none;">
             <div class="headRow">
                <div class="divCell" align="center">Asignatura</div>
                <div  class="divCell">Informaci&oacute;n</div>
             </div>
            <div class="divRow">
                <div class="divCell">Administraci&oacute;n de sistemas operativos. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=33">+info</a></div>
					</div>
				</div>
            </div>
            <div class="divRow">
                 <div class="divCell">Servicios de red e Internet. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=37">+info</a></div>
					</div>
				</div>
           </div>
            <div class="divRow">
               <div class="divCell">Implantaci&oacute;n de aplicaciones web.  </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=41">+info</a></div>
					</div>
				</div>
           </div>
		   <div class="divRow">
               <div class="divCell">Administraci&oacute;n de sistemas gestores de bases de datos. </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=45">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Seguridad y alta disponibilidad.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=48">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Empresa e iniciativa emprendedora.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2009/11/18/pdfs/BOE-A-2009-18355.pdf#page=61">+info</a></div>
					</div>
				</div>
           </div>

      </div>
	 </div>
