<a href="index.php?dep=inf">Atr&aacute;s</a>
<h1>Ciclo Formativo Desarrollo de Aplicaciones Web</h1>
<script type="text/javascript">
 var cambiar = {
    accion:  function(hide, show){ this.ocultar(hide); this.mostrar(show); },
    ocultar: function(num){ document.getElementById("div"+num).style['display'] = "none"; },
    mostrar: function(num){ document.getElementById("div"+num).style['display'] = "block"; }
 };
</script>

<div style="text-align:left; padding:10px;">
<span class="indicepag">
<h2>Informaci&oacute;n de interes</h2>
 El alumno al terminar ser&aacute; capaz de:
 <ul>
 <li> Desarrollar aplicaciones inform&aacute;ticas, participando en el dise&ntilde;o y realizando la programaci&oacute;n, pruebas y documentaci&oacute;n de las mismas de 
                    conformidad con los requisitos funcionales.</li>
<li> Utilizar sistemas inform&aacute;ticos aislados o interconectados en red.</li>
<li> Elaborar, adaptar y probar programas en lenguajes de programaci&oacute;n estructurados 
                    y de cuarta generaci&oacute;n.</li>
<li> Dise&ntilde;ar  y realizar servicios de presentaci&oacute;n que faciliten la explotaci&oacute;n 
                    de aplicaciones.</ul>
Puestos de trabajo que pueden desempe&ntilde;ar:
 <ul>
 <li> Analista 
                    programador de aplicaciones</li>
                 <li>
                    Administrador de SGBD relacionales</li>
                  <li>
                    Gestor de proyectos</li>
                <li>
                    Programador de aplicaciones de gesti&oacute;n. </li>
                  <li>
                    Comercial cualificado de productos inform&aacute;ticos. </li>
					</ul>
<h2>Modulos/Asignaturas</h2>
<button onclick="cambiar.accion(2,1)" class="boton_cambio primercurso">Primer Curso</button>
<button onclick="cambiar.accion(1,2)" class="boton_cambio segundocurso">Segundo curso</button>
  <div class="divTable" id="div1">
             <div class="headRow">
                <div class="divCell" align="center">Asignatura</div>
                <div  class="divCell">Informaci&oacute;n</div>
             </div>
            <div class="divRow">
                <div class="divCell">Sistemas inform&aacute;ticos.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=11">+info</a></div>
					</div>
				</div>
            </div>
            <div class="divRow">
                 <div class="divCell">Programaci&oacute;n.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=19">+info</a></div>
					</div>
				</div>
           </div>
            <div class="divRow">
               <div class="divCell">Lenguajes de marcas y sistemas de gesti&oacute;n de informaci&oacute;n.</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=24">+info</a></div>
					</div>
				</div>
           </div>
		   <div class="divRow">
               <div class="divCell">Bases de Datos </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=15">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Entornos de Desarrollo</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=28">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Formaci&oacute;n y orientaci&oacute;n laboral</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=52">+info</a></div>
					</div>
				</div>
           </div>

      </div>
  <div class="divTable" id="div2"  style="display: none;">
             <div class="headRow">
                <div class="divCell" align="center">Asignatura</div>
                <div  class="divCell">Informaci&oacute;n</div>
             </div>
            <div class="divRow">
                <div class="divCell">Desarrollo web en entorno cliente </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=32">+info</a></div>
					</div>
				</div>
            </div>
            <div class="divRow">
                 <div class="divCell">Desarrollo web en entorno servidor</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=36">+info</a></div>
					</div>
				</div>
           </div>
            <div class="divRow">
               <div class="divCell">Despliegue de aplicaciones web </div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a  target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=41">+info</a></div>
					</div>
				</div>
           </div>
		   <div class="divRow">
               <div class="divCell">Dise&ntilde;o de interfaces web</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a  target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=45">+info</a></div>
					</div>
				</div>
           </div> 
		   <div class="divRow">
               <div class="divCell">Empresa e iniciativa emprendedora</div>
                <div class="divCell2">
					<div class="divRow">
					<div class="divCell"><a target="_blank" href="http://www.boe.es/boe/dias/2010/06/12/pdfs/BOE-A-2010-9269.pdf#page=56">+info</a></div>
					</div>
				</div>
           </div>

      </div>
	 </div>
