<div id='cuerpo-centro'>
  <h1>SECRETARY OFFICE</h1>
  <hr />
  <p class="enc2">Office Hours:</p>
  <p>General: monday to friday about 10:00 h. to 13:00 h.</p>
  <p>Students: monday to friday about 11.15 h. to 11.45 h.</p>
  <p class="enc2">Center Code:</p>
  <span class="texto">28020703</span>
  <p class="enc2">Textbooks (2013-2014)</p>
  <a href="Inicio/Secretaria/Libros_texto.pdf"><img src="Inicio/Secretaria/descarga.png" width="100px" height="100px"></img></a>
</div>
