
<div id='cuerpo-centro'>
	<h1 id="tit">Periódicos del IES Enrique Tierno Galvan</h1>
		
		<div id="primero"><a href="javascript:anterior()"><img id="flecha1" src="Periodicos/Inicio/anterior.png"></a></div>
		
		<div id="segundo">
			<ul class="hoverbox">
				<li>
					<a id="una-dos" href="Periodicos/Inicio/Periodicos/1.pdf" target="_blank"><img name="una" src="Periodicos/Inicio/capturas/1.jpg" alt="description" title="periodico 1" /><img name="una-una" src="Periodicos/Inicio/capturas/1.jpg" title="periodico 1"alt="description" class="preview" /></a>
				</li>
				
				<li>
					<a  id="dos-dos" href="Periodicos/Inicio/Periodicos/2.pdf"target="_blank"><img name="dos" src="Periodicos/Inicio/capturas/2.jpg" alt="description" /><img name="dos-una" src="Periodicos/Inicio/capturas/2.jpg" alt="description" class="preview" /></a>
				</li>
				
				<li>
					<a id="tres-dos" href="Periodicos/Inicio/Periodicos/3.pdf"target="_blank"><img name="tres" src="Periodicos/Inicio/capturas/3.jpg" alt="description" /><img name="tres-una" src="Periodicos/Inicio/capturas/3.jpg" alt="description" class="preview" /></a>
				</li>
				
				<li>
					<a id="cuatro-dos" href="Periodicos/Inicio/Periodicos/4.pdf"target="_blank"><img name="cuatro" src="Periodicos/Inicio/capturas/4.jpg" alt="description" /><img name="cuatro-una" src="Periodicos/Inicio/capturas/4.jpg" alt="description" class="preview" /></a>
				</li>
			</ul>
		</div>
		<div id="tercero"><a href="javascript:siguiente()"><img id="flecha2" src="Periodicos/Inicio/sigiente.png"></a></div>
		<h3 id="pag">Página 1 de 5</h3>

</div>
