<?php

/**
 *
 * @author daw
 */

namespace controller;

class SqlQuery {

    //Consumer
    const CONSUMER_KEY = "ConsumerKey";
    const CONSUMER_SECRET = "ConsumerSecret";
    //Token
    const OAUTH_TOKEN = "oauth_token";
    const OAUTH_TOKEN_SECRET = "oauth_token_secret";
    const USER_ID = "user_id";
    const SCREEN_NAME = "screen_name";
    const X_AUTH_EXPIRES = "x_auth_expires";
    const ID = "ID";
    const NOMBRE = "NOMBRE";
    const FECHA_NACIMIENTO = "FECHA_NACIMIENTO";
    const MAYOR_EDAD = "MAYOR_EDAD";
    const DISPONIBLE = "DISPONIBLE";
    const RATIO_DISPONIBLE = "RATIO_DISPONIBLE";
    const SELECT_ALL_TWITTER_APP = "SELECT * FROM TWITTER_APP";
    const SELECT_STATUS_USER_BY_IP = "SELECT  USER_COUNTER.UPDATE_STATUS,USER_COUNTER.COUNT_POST FROM USER_COUNTER "
            . "WHERE USER_COUNTER.FECHA = CURRENT_DATE() AND USER_COUNTER.IP_ADDRESS = ?;";
    const SELECT_ALL_TWITTER_TOKEN_ASUKA = "SELECT * FROM TWITTER_TOKEN_ASUKA";
    const INSERT_INTO_USER_ACCESS = "INSERT INTO `USERS_ACCESS` (`USER_ACCESS_ID`, `IP`, `AGENTE`, `FECHA`) VALUES (NULL, ?, ?, CURRENT_TIME());";
    const SELECT_RATIO_AND_LIMIT_DAY = "SELECT  RATIO_TWEET.RATIO_DISPONIBLE, CONTADOR.DISPONIBLE FROM CONTADOR,RATIO_TWEET "
            . "WHERE CONTADOR.FECHA = CURRENT_DATE() AND RATIO_TWEET.FECHA_RATIO = CURRENT_DATE();";

}
