<?php
echo "
<div id='cuerpo-centro'>
<h1>TEACHINGS</h1>
<hr />
<div class='ensenanzas_izquierda'>
<ul class='ensenanzas_ul'>
  <li class='ensenanzas_titulo'>E.S.O. (four courses)</li>
    <ul>
      <li>First course of E.S.O.</li>
      <li>Second course of E.S.O.</li>
      <li>Third course of E.S.O.</li>
      <li>Fourth course of E.S.O.</li>
    </ul>

  <li class='ensenanzas_titulo'>Bachilleratos (two courses)</li>
    <ul>
      <li>Science and technology(in the morning)</li>
      <li>Humanities and Social Studies(in the morning)</li>
    </ul>

  <li class='ensenanzas_titulo'>Vocational Training</li>
    <ul>
      <li class='ensenanzas_subtitulo'>Programs of Professional Initial Qualification (one course)</li>
        <ul>
          <li>Auxiliary operations of assembly of facilities in buildings (in the evening)</li>
          <li>Operations of plumbing and heating-air conditioning (in the evening)</li>
          <li>Auxiliary operations in maintenance of vehicles (in the evening)</li>
        </ul>

      <li class='ensenanzas_subtitulo'>Cycles of Average Degree (two courses)</li>
        <ul>
          <li>Electronic equipments of consumption<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
          <li>Electrical and automatic facilities<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
          <li>Facilities of heat production<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: only 2&#176;</li>
          <li>Refrigerating facilities and of air conditioning<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: only 2&#176;</li>
	  <li>Facilities of heat production, refrigerating and of air conditioning<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning and in the evening<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; y 2&#176;</li>
          <li>Auto body<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
        </ul>

      <li class='ensenanzas_subtitulo'>Cycles of Top Degree (two courses)</li>
        <ul>
          <li>Administration of IT systems in network<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the evening<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
          <li>Development of web applications<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the morning<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
          <li>Maintenance of thermal facilities and of fluids<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the evening<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
          <li>Automotion<br>
			  <span class='ensenanzas_subrayado'>Schedule</span>: in the evening<br>
			  <span class='ensenanzas_subrayado'>Courses</span>: 1&#176; and 2&#176;</li>
        </ul>

    </ul>
</ul>
</div>

<h1>SCHEDULE</h1>
<hr size='5' width='600' color='white' />
<div class='ensenanzas_izquierda'>
<ul class='ensenanzas_ul'>
  <li class='ensenanzas_titulo'>Morning</li>
	  <span class='ensenanzas_subrayado'>Schedule</span>: from 8:30 to 14:30 being able to be included some hour (tutorship, ...) from 14:35 to 15:30. Playtime from 11:15 to 11:45.
  <li class='ensenanzas_titulo'>Evening (in the afternoon)</li>
	  <span class='ensenanzas_subrayado'>Schedule</span>: from 15:30 to 21:30. Playtime from 18:15 to 18:45.
</ul>
</div>
</div>
"
?>
