<?php
echo "
<div id='cuerpo-centro'>
<h1>ENSEÑANZAS</h1>
<hr />
<div class='ensenanzas_izquierda'>
<ul class='ensenanzas_ul'>
  <li class='ensenanzas_titulo'>E.S.O. (cuatro cursos)</li>
    <ul>
      <li>Primer Curso de E.S.O.</li>
      <li>Segundo Curso de E.S.O.</li>
      <li>Tercer Curso de E.S.O.</li>
      <li>Cuarto Curso de E.S.O.</li>
    </ul>

  <li class='ensenanzas_titulo'>Bachilleratos (dos cursos)</li>
    <ul>
      <li>Ciencias y Tecnología(por la mañana)</li>
      <li>Humanidades y Ciencias Sociales(por la mañana)</li>
    </ul>

  <li class='ensenanzas_titulo'>Formación Profesional</li>
    <ul>
      <li class='ensenanzas_subtitulo'>Programas de Cualificación Profesional Inicial (un curso)</li>
        <ul>
          <li>Operaciones auxiliares de montaje de instalaciones en edificios (por la tarde)</li>
          <li>Operaciones de fontanería y calefacción-climatización (por la tarde)</li>
          <li>Operaciones auxiliares en mantenimiento de vehículos (por la tarde)</li>
        </ul>

      <li class='ensenanzas_subtitulo'>Ciclos de Grado Medio (dos cursos)</li>
        <ul>
          <li>Equipos electrónicos de consumo<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Instalaciones eléctricas y automáticas<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Instalaciones de producción de calor<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: sólo 2&#176;</li>
          <li>Instalaciones frigoríficas y de climatización<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: sólo 2&#176;</li>
	  <li>Instalaciones de producción de calor, frigoríficas y de climatización<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana y por la tarde<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Carrocería<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
        </ul>

      <li class='ensenanzas_subtitulo'>Ciclos de Grado Superior (dos cursos)</li>
        <ul>
          <li>Administración de sistemas informáticos en red<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la tarde<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Desarrollo de aplicaciones web<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la mañana<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Mantenimiento de instalaciones térmicas y de fluidos<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la tarde<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
          <li>Automoción<br>
			  <span class='ensenanzas_subrayado'>Horario</span>: por la tarde<br>
			  <span class='ensenanzas_subrayado'>Cursos</span>: 1&#176; y 2&#176;</li>
        </ul>

    </ul>
</ul>
</div>

<h1>HORARIO</h1>
<hr size='5' width='600' color='white' />
<div class='ensenanzas_izquierda'>
<ul class='ensenanzas_ul'>
  <li class='ensenanzas_titulo'>Mañana</li>
	  <span class='ensenanzas_subrayado'>Horario</span>: de 8:30 a 14:30 pudiéndose incluir alguna hora (tutoría, ...) de 14:35 a 15:30. Recreo de 11:15 a 11:45.
  <li class='ensenanzas_titulo'>Vespertino (por la tarde)</li>
	  <span class='ensenanzas_subrayado'>Horario</span>: de 15:30 a 21:30. Recreo de 18:15 a 18:45.
</ul>
</div>
</div>
"
?>
