<div id='cuerpo-centro'>
  <h1>DISEÑOS WEB</H1>
  <hr />
  <div style="text-align: left;">
    <H3><u>Curso 2015-16 DAW 2</u></H4>
    <ul style="list-style-image:url(imagenes/ok.png);">
      <li> Pablo García Fullana (<a href="Alumnos/Disenos/2015_16_Daw2/GarciaP/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_01/departamentos">Departamentos</a>)</li>
      <li> Yingying Hu (<a href="Alumnos/Disenos/2015_16_Daw2/HuY/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_03/departamentos">Departamentos</a>)</li>
      <li> Yevhen Letin (<a href="Alumnos/Disenos/2015_16_Daw2/LetinY/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_04/departamentos">Departamentos</a>)</li>
      <li> Alberto Marcos Olmeda (<a href="Alumnos/Disenos/2015_16_Daw2/MarcosA/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_07/departamentos">Departamentos</a>)</li>
      <li> Valentin Minca (<a href="Alumnos/Disenos/2015_16_Daw2/MincaV/index.html">Portada</a>) 
           (<a href="http://www.educa2.madrid.org/web/daw2_08/departamentos">Departamentos</a>)</li>
      <li> Patricia Peña (<a href="Alumnos/Disenos/2015_16_Daw2/PenaP/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_09/departamentos">Departamentos</a>)</li>
      <li> Mario Pulido Leno (<a href="Alumnos/Disenos/2015_16_Daw2/PulidoM/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_10/departamentos">Departamentos</a>)</li>
      <li> Alba Recio Sansón (<a href="Alumnos/Disenos/2015_16_Daw2/RecioA/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_11/departamentos">Departamentos</a>)</li>
      <li> Alejandro Rubio Ramos (<a href="Alumnos/Disenos/2015_16_Daw2/RubioA/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_12/departamentos">Departamentos</a>)</li>
      <li> Jonathan Salazar Lozano (<a href="Alumnos/Disenos/2015_16_Daw2/SalazarJ/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_13/departamentos">Departamentos</a>)</li>
      <li> Guillermo Ernesto Valenzuela Alía (<a href="Alumnos/Disenos/2015_16_Daw2/ValenzuelaG/index.html">Portada</a>)
           (<a href="http://www.educa2.madrid.org/web/daw2_14/departamentos">Departamentos</a>)</li>
    </ul>

  </div>

</div>

