<?php
echo "
<div id='cuerpo-centro'>
<h1>ADMINISTRATION</h1>
<!-- <ul class='lista_grande'>
  <li><a href='#'>Erasmus Project</a></li>
  <li><a href='#'>Job Vacancies</a></li>
  <li><a href='#'>Textbooks</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Examenes_septiembre.pdf'>Exams of September</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Sesiones_eval.pdf'>Evaluation Sessions</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Calendario_septiembre.pdf'>Calendar of September</a></li>
</ul> -->
</div>
"
?>