<?php
echo "
<div id='cuerpo-centro'>
<h1>ADMINISTRACI&Oacute;N</h1>
<!-- <ul class='lista_grande'>
  <li><a href='#'>Proyecto Erasmus</a></li>
  <li><a href='#'>Bolsa de trabajo</a></li>
  <li><a href='#'>Libros de texto</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Examenes_septiembre.pdf'>Exámenes de Septiembre</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Sesiones_eval.pdf'>Sesiones de evaluación</a></li>
  <li><a href='http://www.tiernogalvan.es/Inicio/Inicio/Calendario_septiembre.pdf'>Calendario de Septiembre</a></li>
</ul> -->
</div>
"
?>