<div id='cuerpo-centro'>
  <h1>SECRETARÍA</h1>
  <hr />
  <p class="enc2">Horario de Secretar&iacute;a:</p>
  <span class="texto">
    <p>General: de lunes a viernes de 10:00 h. a 13:00 h.</P>
    <p>Para alumnos: de lunes a viernes de 11.15 h. a 11.45 h.</p>
  </span>
  <br>
  <p class="enc2">Codigo del Centro:</p>
  <span class="texto">28020703</span>
  <p class="enc2">Libros de Texto (2013-2014)</p>
  <a href="Inicio/Secretaria/Libros_texto.pdf"><img src="Inicio/Secretaria/descarga.png" width="100px" height="100px"></img></a>
</div>
