<div id='cuerpo-centro'>
  <h1>CONTACT</h1>
  <hr />
  <div class="Contac_Div">
    <ul class="Contac_lista">
      <li class="Contac_titulo">Address</li>
      <li>IES Enrique Tierno Galvan</li>
      <li>Avda. Andalucía Km. 6,200</li>
      <li>28041 Madrid - Spain</li>
      <li>IES Enrique Tierno Galvan</li>
      <li> <a href='https://maps.google.es/maps? f=d&source=s_d&saddr=40.370155,-3.694671&daddr=&geocode=&sll=40.368733,-3.691664&sspn=0.013357,0.01929&hl=es&mra=mift&mrsp=0&sz=16&ie=UTF8&t=m&ll=40.368733,-3.691664&spn=0.013357,0.01929' onclick='nuevaventana("https://maps.google.es/maps?f=d&source=s_d&saddr=40.370155,-3.694671&daddr=&geocode=&sll=40.368733,-3.691664&sspn=0.013357,0.01929&hl=es&mra=mift&mrsp=0&sz=16&ie=UTF8&t=m&ll=40.368733,-3.691664&spn=0.013357,0.01929")' 
						target='_blank'>See location on Maps</a>
      </li>
    </ul>
  </div>
  <div class='Contac_Div'>
	<p class="Contac_titulo">Phone & Fax</p>
	<p style='margin-left:9px;'><img src='Comun/imagenes/contacto/telefono.png' align="middle"/> 91 317 00 47 &nbsp;&nbsp;&nbsp;
	<img src='Comun/imagenes/contacto/fax.png' align="middle"/ > 91 317 35 29</p>
  </div>
  <div class='Contac_Div'>
	<p class="Contac_titulo">Email</p>
	<p style='margin-left:9px;'><img src='Comun/imagenes/contacto/E-mail.png' align="middle"/ >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="ies.tiernogalvan.madrid@educa.madrid.org  ">ies.tiernogalvan.madrid@educa.madrid.org</a></p>
  </div>
  <div class='Contac_Div'>
	<p class="Contac_titulo">How to arrive</p>
	<p style='margin-left:9px;'><img src='Comun/imagenes/contacto/logo_metro.png' align="middle"/> 		San Fermin-Orcasur L3 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="Comun/imagenes/contacto/mapas-madrid-metro-underground.jpg" target='_blank';>See Underground map</a></p>
	<p style='margin-left:18px;'><img src='Comun/imagenes/contacto/emt.png' align="middle"/> 		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  18 - 22 - 59 -76 - 79 - 85 - 86 </p>
  </div>
</div>
