<?php
echo "
<div id='cuerpo-centro'>
<h1>CONTACT</h1>
<hr size='5' width='600' color='white' />
Tfno: 91 317 00 47 <br>
Adress: Avda. Andalucía Km. 6,200

<p><iframe width='425' height='350' frameborder='0' scrolling='no' marginheight='0' marginwidth='0' src='https://maps.google.es/maps?f=d&amp;source=s_d&amp;saddr=40.370155,-3.694671&amp;daddr=&amp;geocode=&amp;sll=40.368733,-3.691664&amp;sspn=0.013357,0.01929&amp;hl=es&amp;mra=mift&amp;mrsp=0&amp;sz=16&amp;ie=UTF8&amp;t=m&amp;ll=40.368733,-3.691664&amp;spn=0.013357,0.01929&amp;output=embed'></iframe><br /><small><a href='https://maps.google.es/maps?f=d&amp;source=embed&amp;saddr=40.370155,-3.694671&amp;daddr=&amp;geocode=&amp;sll=40.368733,-3.691664&amp;sspn=0.013357,0.01929&amp;hl=es&amp;mra=mift&amp;mrsp=0&amp;sz=16&amp;ie=UTF8&amp;t=m&amp;ll=40.368733,-3.691664&amp;spn=0.013357,0.01929' style='color:#0000FF;text-align:left'>Ver mapa más grande</a></small></p>

</div>
"
?>