<div id="cuerpo-centro">
  <center>
  <h1>EQUIPO DIRECTIVO</h1>
  <div class="iniadconfondo">
    <div valign="middle" class="iniadconfm1">
      &nbsp;&nbsp;
      <font class="iniadconmenu1">Composici&oacute;n y funciones</font>
    </div>

    <div align="middle" class="iniadconclase">
      <br>
      <font class=iniadcon_titulos>Directora: </font>
      <font class="iniadcon_nombres">D&ntilde;a. Sagrario del Olmo<br><br></font>
      <font class=iniadcon_titulos>Funciones: </font>
      Dirige y coordina todas las actividades del Instituto, cumple y hace cumplir las leyes
      y demás disposiciones vigentes.
      <br><br>
    </div>
    <div valign="middle" class="iniadconclase" >
      <br>
      <font class=iniadcon_titulos>Jefa de estudios de mañana: </font>
      <font class=iniadcon_nombres>D&ntilde;a. Marta Melo</font>
      <br>
      <font class=iniadcon_titulos>Jefe de estudios de tarde: </font>
      <font class=iniadcon_nombres>D. Antonio Ponce</font>
      <br><br>
      <font class=iniadcon_titulos>Funciones: </font>
      Ejercen la jefatura del personal docente en todo lo relativo al regimen
      del instituto, organizan los actos academicos, etc.
      <br><br>
    </div>
    <div class=iniadconclase>
      <br>
      <font class="iniadcon_titulos">Jefes de Estudios adjuntos y Secretario</font>
      <font class=parr31><br></font>
      <div align=left>
        <ul>
          <font class="iniadcon_nombres"><li>D&ntilde;a. Elena Ramos: </font>
          <font class="iniadcon_titulos"> Jefa de estudios adjunta</font>
           <br>
          <font class="iniadcon_nombres"><li>D&ntilde;a. Amparo Albir: </font>
          <font class="iniadcon_titulos"> Jefa de estudios adjunta</font>
           <br>
          <font class="iniadcon_nombres"><li>D&ntilde;a. Elena Ponte-Lira: </font>
          <font class="iniadcon_titulos"> Jefa de estudios adjunta</font>
           <br>
          <font class="iniadcon_nombres"><li>D. Roberto Anton: </font>
          <font class="iniadcon_titulos"> Secretario</font>
           <br><br>
        </ul>
      </div>
    </div>
  </div>
</div>
