<div id="cuerpo-centro">
  <center>
  <h1>MANAGEMENT TEAM</h1>
  <div class="iniadconfondo">
    <div valign="middle" class="iniadconfm1">
      &nbsp;&nbsp;
      <font class="iniadconmenu1">Composition and functions</font>
    </div>

    <div align="middle" class="iniadconclase">
      <br>
      <font class=iniadcon_titulos>Director: </font>
      <font class="iniadcon_nombres">Ms. Sagrario del Olmo<br><br></font>
      <font class=iniadcon_titulos>Functions: </font>
      Represents the institute, complying with and enforcing the laws, who directs and coordinates all activities of the college.
      <br><br>
    </div>
    <div valign="middle" class="iniadconclase" >
      <br>
      <font class=iniadcon_titulos>The morning Head of Studies: </font>
      <font class=iniadcon_nombres>Ms. Marta Melo</font>
      <br>
      <font class=iniadcon_titulos>The evening Head of Studies: </font>
      <font class=iniadcon_nombres>Mr. Antonio Ponce</font>
      <br><br>
      <font class=iniadcon_titulos>Functions: </font>
      Exercises authority over the teachers and students in all matters relating to academic regime, coordinates all academic activities
      and ensures the pedagogical action in high school, replaces the director in case of absence or illness.
      <br><br>
    </div>
    <div class=iniadconclase>
      <br>
      <font class="iniadcon_titulos">Deputy Head and Secretarie</font>
      <font class=parr31><br></font>
      <div align=left>
        <ul>
          <font class="iniadcon_nombres"><li>Ms. Elena Ramos: </font>
          <font class="iniadcon_titulos"> Deputy Director of Studies for ESO</font>
           <br>
          <font class="iniadcon_nombres"><li>Ms. Amparo Albir: </font>
          <font class="iniadcon_titulos"> Deputy Chief of Baccalaureate Studies</font>
           <br>
          <font class="iniadcon_nombres"><li>Ms. Elena Ponte-Lira: </font>
          <font class="iniadcon_titulos"> Deputy Head of the Management Studies</font>
           <br>
          <font class="iniadcon_nombres"><li>Mr. Roberto Anton: </font>
          <font class="iniadcon_titulos"> Secretary</font>
           <br><br>
        </ul>
      </div>
    </div>
  </div>
</div>

