<?php
echo "
<div id='cuerpo-dcha'><br>
	<center><p style='color:black;font-size:20px;font-weight:bold;'>Carta Erasmus Actual</p>
	<a href='Erasmus/pdf/CartaErasmusNueva.pdf' target='_blank'><img style=' height:160px;width:160px;'src='Erasmus/img/capturaCartaErasmusNueva.jpg'/></center></a>
	<br>
	<center><p style='color:black;font-size:20px;font-weight:bold;'>Carta Erasmus Antigua</p>
	<a href='Erasmus/pdf/erasmus1.jpg' target='_blank'><img style='width:90%;'src='Erasmus/img/cartalogo2.jpg'/></center></a>

</div>
";
?>
