<?php
echo "
<div id='cuerpo-centro'>
	<br>
	<img src='Erasmus/img/erasmus.png'/><br>
	<p ALIGN='left'>Nuestro centro viene participando en programas de movilidad en Enseñanza Superior desde la concesi&oacute;n de la carta Erasmus en el año 2013.<br><br>
	En enero de 2014 ha entrado en vigor el nuevo programa Erasmus+, aprobado por el parlamento Europeo, que se extiende hasta el año 2020.<br><br>
	Se nos ha permitido de nuevo la posibilidad de participar en este programa, concedi&eacute;ndonos la nueva carta Erasmus para el per&iacute;odo 2014-2020.<br><br>
	Este nuevo programa se centra en el aprendizaje formal e informal m&aacute;s allá de las fronteras de la EU, con una clara vocaci&oacute;n de internacionalizaci&oacute;n abri&eacute;ndose a terceros pa&iacute;ses con el objetivo de mejorar las capacidades educativas y formaticas de las personas para la empleadbilidad de estudiantes, profesorado y trabajadores y trabajadoras.<br><br>
	En materia educatica abarca todos los niveles: escolar, formaci&oacute;n, enseñanza superior y formaci&oacute;n de personas adultas (<a href='http://www.oapee.es/oapee/inicio.html'>ver+</a>).<br>
<div align='left'>
 <strong><span style='color: #0000ff;'>Resultados curso 2013-2014</span></strong><br><br>
 Hemos llevado a cabo 5 movilidades SMP:<br>
 <ul>
   <li>Se nos concedieron 4 becas.</li>
   <li>1 alumno con beca 0 (pero se nos ha concedido tambi&eacute;n !!!).</li>
 </ul>
 Los alumnos seleccionados, seg&uacute;n las bases de la convocatoria, estaban matriculados en los siguientes Ciclos Formativos de Grado Superior:<br>
 <ul>
   <li>ADMINISTRACI&Oacute;N DE SISTEMAS INFORM&Aacute;TICOS EN RED (1 alumno)</li>
   <li>MANTENIMIENTO DE INSTALACIONES T&Eacute;RMICAS Y DE FLUIDOS (4 alumnos)</li>
 </ul>
Las pr&aacute;cticas las han realizado en empresas localizadas en Dubl&iacute;n y Galway (Irlanda), estando acreditadas, igual que el m&oacute;dulo de Formaci&oacute;n en el Centro de trabajo, con 22 cr&eacute;ditos<a href='http://www.madrid.org/eees/acap/suplemento/Caracteristicas_esenciales.pdf' target='_blank' title='Cr&eacute;ditos ECTS'> ECTS</a>.<br><br>
Dos de nuestros alumnos&nbsp; de MITF han conseguido contrato, uno en Dubl&iacute;n y otro en Galway.</p>
</div>
	<div id='listas'  align='left'>	
		<ul margin=left >
			<li class='lis'>PROYECTOS ESCOLARES</li>
			
			<li class='lis'>MOVILIDAD DE ESTUDIOS/PR&Aacute;CTICAS>
				<ul>
					<li class='lis2'><a href='Erasmus/pdf/seguro.pdf' target='_blank'>Seguro de FCT</a></li>
					<li class='lis2'><a href='Erasmus/pdf/convocatoria.pdf' target='_blank'>Bases de convocatoria curso 2013</a></li>
					<li class='lis2'><a href='#'>Documentaci&oacute;n de la convocatoria curso 2013</a></li>
				</ul>
			</li>
			<li class='lis'>MOVILIDADES VET</li>
			<li class='lis'>POL&Iacute;TICA DE INTERNACIONALIZACI&Oacute;N>
				<ul>
					<li class='lis2'><a href='Erasmus/pdf/politica.pdf' target='_blank'>Pol&iacute;tica lingüistica</a></li>
					
				</ul>
			</li>
		</ul>
	</div>
</div>
"
?>
