<div id='cuerpo-izda'>

<!---------------------------------- Anulado 20 - Oct - 2014 ---------------------------------
    Imagen enlace a bolsa de trabajo internacional
  <center>
    <a href='http://localhost/index.php?era_form' target='_self'>BOLSA DE TRABAJO<BR>
    INTERNACIONAL<img style=' height:160px; width:160px;'src='Erasmus/LOGO.png'/></a>
  </center>

  <center>
    <a style='text-decoration:none' id='Erasmus_Bolsa' href='#' target='_self'>
    <img src='Erasmus/img/bolsa.jpg' width=180px height=120px></a>
    <img onclick = 'mostrar_bolsaint()' src='Erasmus/img/bolsa.jpg' width=180px height=120px></a>
  </center>
--------------------------------------------------------------------------------------------->
<br /><br />
<center>
BÚSQUEDA DE EMPLEO:<br />
</center>
<ul>
  <li><a href="http://www.sepe.es/contenidos/personas/encontrar_empleo/empleo_europa.html">Servicio público de empleo europeo</a></li>
  <li><a href="https://ec.europa.eu/eures/page/homepage?lang=es">Red Eures</a></li>
</ul>
<br />
  <center>
<a style='text-decoration:none' id='Erasmus_Form' href='http://localhost/index.php?era_form' target='_self'>
    <img src='Erasmus/img/formu.jpg' width=180px height=120px></a>
    <!--img onclick = 'mostrar_plazo()' src='Erasmus/img/formu.jpg' width=180px height=120px></a-->
  </center>
</div>

