<div id="cuerpo-centro">
  <center>
    <h1>CONSEJO ESCOLAR</h1>
    <div class="iniadconfondo">
    <div valign="middle" class="iniadconfm1">
       &nbsp;&nbsp;<font class="iniadconmenu1">
       <font class="iniadconmenu1">
    Composición
       </font>
    </div>



<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Presidenta: </font> <br><br>

<font class="iniadcon_nombres"> D&ntilde;a. M&ordf; del Sagrario del Olmo</font>
<br><br>
</div>




<div valign="middle" class="iniadconclase" ><br><font class=iniadcon_titulos>
Jefes de estudios: </font><br><br>

<font class="iniadcon_nombres">D&ntilde;a. Marta Melo</font> <br>
<font class="iniadcon_nombres">D. Antonio Ponce</font> <br>

</div>



<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Representantes de profesores: </font><br><br>

<font class="iniadcon_nombres">D. Santiago Alonso</font><br>

<font class="iniadcon_nombres">D&ntilde;a. Eva Garc&iacute;a </font><br>

<font class="iniadcon_nombres">D&ntilde;a. Justa Mac&iacute;as </font><br>

<font class="iniadcon_nombres">D. Emilio Romero </font><br>

<font class="iniadcon_nombres">D&ntilde;a.Mercedes Bola&ntilde;os </font><br>

<font class="iniadcon_nombres">D. Sergio Antonio Iglesias </font><br>

<font class="iniadcon_nombres">D.Jes&uacute;s Nieto </font><br>
<br><br>
</div>




<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Representantes de la administracion y servicios: </font><br><br>

<font class="iniadcon_nombres">D. &Aacute;ngel Rodero </font>
<br><br>
</div>

<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Representantes de padres: </font><br><br>

<font class="iniadcon_nombres">D. &Aacute;ngel Mart&iacute;n </font><br>
<font class="iniadcon_nombres">D&ntilde;a. Mar&iacute;a Isabel Mu&ntilde;oz </font><br>
<br><br>
</div>





<div class=iniadconclase>
<font class="iniadcon_titulos"> Representantes de los alumnos:</font><br><br>



	<font class="iniadcon_nombres">D&ntilde;a. Margarita Bolobaha</font><br>
	<font class="iniadcon_nombres">D. Israel Garc&iacute;</font>a<br>
	<font class="iniadcon_nombres">D.Alejandro Oca&ntilde;a</font><br>
	<font class="iniadcon_nombres">D&ntilde;a. Alicia Vena</font><br>



<br>

</div>

</div>

</div>




