<div id="cuerpo-centro">
  <center>
    <h1>THE SCHOOL BOARD</h1>
    <div class="iniadconfondo">
      <div valign="middle" class="iniadconfm1">
       &nbsp;&nbsp;<font class="iniadconmenu1">
        <font class="iniadconmenu1">
             Compoused:
        </font>
      </div>

<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
President: </font> <br><br>

<font class="iniadcon_nombres">Ms M&ordf; del Sagrario del Olmo</font>
<br><br>
</div>




<div valign="middle" class="iniadconclase" ><br><font class=iniadcon_titulos>
Head of Studies: </font><br><br>

<font class="iniadcon_nombres">Ms Marta Melo</font> <br>
<font class="iniadcon_nombres">Mr Antonio Ponce</font> <br>

</div>



<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Representatives of teachers: </font><br><br>

<font class="iniadcon_nombres">Mr. Santiago Alonso </font><br>

<font class="iniadcon_nombres">Ms. Eva Garc&iacute;a </font><br>

<font class="iniadcon_nombres">Ms. Justa Mac&iacute;as </font><br>

<font class="iniadcon_nombres">Mr. Emilio Romero </font><br>

<font class="iniadcon_nombres">Ms. Mercedes Bola&ntilde;os </font><br>

<font class="iniadcon_nombres">Mr. Sergio Antonio Iglesias </font><br>

<font class="iniadcon_nombres">Mr. Jes&uacute;s Nieto </font><br>
<br><br>
</div>




<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Representatives of the Administration and Services: </font><br><br>

<font class="iniadcon_nombres">Mr. &Aacute;ngel Rodero </font>
<br><br>
</div>

<div valign="middle" class="iniadconclase"><br><font class=iniadcon_titulos>
Parent representatives: </font><br><br>

<font class="iniadcon_nombres">Mr. &Aacute;ngel Mart&iacute;n </font><br>
<font class="iniadcon_nombres">Ms. Mar&iacute;a Isabel Mu&ntilde;oz </font><br>
<br><br>
</div>


<br>


<div class=iniadconclase>
<font class="iniadcon_titulos"> Student representatives:</font><br><br>



	<font class="iniadcon_nombres">Ms. Margarita Bolobaha</font><br>
	<font class="iniadcon_nombres">Mr. Israel Garc&iacute;</font>a<br>
	<font class="iniadcon_nombres">Mr. Alejandro Oca&ntilde;a</font><br>
	<font class="iniadcon_nombres">Ms. Alicia Vena</font><br>



<br>

</div>

</div>

</div>



