<div id='cuerpo-centro'>
  <h1>DOCUMENTOS</H1>
  <hr />
  <div style="text-align: left;">
    <H3><u>General</u></H4>
    <ul style="list-style-image:url(imagenes/ok.png);">
      <!--li><a href="/evaluaciones">Resultados de evaluaciones.</a></li-->

      <li> <a href="/Jefatura/Documentos/doc/PGA_2015_16.pdf">PGA - Programación General Anual</a></li>

      <li> <a href="/Jefatura/Documentos/doc/Delegados.dot">Acta de
    elecci&oacute;n de Delegados</a></li>

      <li><span style="font-weight: bold;"></span><a href="http://www.madrid.org/cs/Satellite?c=CM_InfPractica_FA&cid=1142649238708&language=es&pagename=PortalEducacion/CM_InfPractica_FA/EDUC_InfPractica">Calendario
    Escolar General del curso 2015/2016</a></li>

      <!--li><span style="font-weight: bold;"></span><a href="CalendarioFCT10.html">Calendario
    FCT del curso 2.009-10</a></li-->

      <!--
    &nbsp; &nbsp; -&nbsp;<span style="font-weight: bold;"></span><a href="Cal_Cic_08.html">Calendario
    Escolar para Ciclos del curso 2.008-09</a><br>

    &nbsp; &nbsp; -&nbsp;<span style="font-weight: bold;"></span><a href="Cal_PCPI_08.html">Calendario
    Escolar para PCPIs del curso 2008-09</a><br>
    -->

      <li> <a href="/Jefatura/Documentos/doc/Parte.xls">Parte
    de amonestaci&oacute;n</a></li>

      <li> <a href="/Jefatura/Documentos/doc/Normas.doc">Normas
    de funcionamiento e informaci&oacute;n del Centro</a></li>

      <!--li> <a href="/ftp/Jefatura/General/Informe.doc">Informe
    individualizado del alumno</a></li-->

      <li> <a href="/Jefatura/Documentos/doc/Informead.doc">Informe
    individualizado del alumno adaptado a este Centro</a></li>

      <li><a href="/Jefatura/Documentos/doc/prog-mem.pdf">Orientaciones para realizar la memoria.</a></li>

      <li><a href="/Jefatura/Documentos/doc/Ejemplo-libro-actas.doc">Ejemplo de libro de actas para departamentos</a></li>
      <li><a href="/Jefatura/Documentos/doc/ValPracticaDocente.doc">Valoraci&oacute;n de la pr&aacute;ctica docente: gu&iacute;a de reflexi&oacute;n</a></li>
      <li><a href="/Jefatura/Documentos/doc/instruc_justifica_ausencias_solo.pdf" >
                Instrucciones de justificaci&oacute;n de ausencias del personal laboral y docente de menos de 4 d&iacute;as
            </a>
      </li>
      <li><a href="/Jefatura/Documentos/doc/a1_fun_lab.pdf">
                Impresos de justificaci&oacute;n ANEXO I
            </a></li>
      <li><a href="/Jefatura/Documentos/doc/a2_fun_lab.pdf">
                Impresos de justificaci&oacute;n ANEXO II
            </a>
      </li>
      <li><a href="/Jefatura/Documentos/doc/a3_fun.pdf">
                Impresos de justificaci&oacute;n ANEXO III
            </a>
      </li>

    </ul>

    <!--H3>E.S.O.</H4-->

    <!--H3>Bachillerato</H4-->

    <H3><u>F.P.</u></H4>

    <!--/small-->

    <H4>Bajas por inasistencia</H4>

    <!--a href="/ftp/Jefatura/Fp/Bajas/Falta5pc.doc">Comunicaci&oacute;n
al faltar el 5% de clases</a><br-->

    <ul style="list-style-image:url(iagenes/ok.png);">
      <li><a href="/Jefatura/Documentos/doc/Falta10pc.doc">Comunicaci&oacute;n
al faltar el 10% de clases</a></li>

      <li><a href="/Jefatura/Documentos/doc/Falta15pc.doc">Comunicaci&oacute;n
al faltar el 15% de clases</a></li>

      <li><a href="/Jefatura/Documentos/doc/Falta10d.doc">Comunicaci&oacute;n
al faltar 10 d&iacute;as consecutivos</a></li>

      <li><a href="/Jefatura/Documentos/doc/Falta15d.doc">Comunicaci&oacute;n
al faltar 15 d&iacute;as consecutivos</a></li>

      <li><a href="/Jefatura/Documentos/doc/Comunicacion.doc">Comunicaci&oacute;n
a Secretar&iacute;a de la propuesta de baja</a></li>

    </ul>

    <h4> <a name="fct">Anexos FCT</a></h4>

    <ul style="list-style-image:url(imagenes/ok.png);">

      <li><a href="/Jefatura/Documentos/doc/VisitaTutor.doc">Anexo 1: Informe visita tutor (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Anexo3.doc">
         Anexo 3: Programa formativo</a></li>
      <li><a href="/Jefatura/Documentos/doc/Anexo4.doc">Anexo 4: Parte semanal de
            actividades del alumno</a></li>
      <li><a href="/Jefatura/Documentos/doc/Anexo5.doc">Anexo 5: Informe del tutor de la
                empresa</a></li>
      <li><a href="/Jefatura/Documentos/doc/Anexo5a.doc">Anexo 5A: Desplazamientos de los
            tutores de FCT</a></li>
      <li>Anexo 5A: Desplazamiento de los tutores (<a href="/Jefatura/Documentos/doc/Anexo_5a_Autorizacion.doc">para Word</a>)
          (<a href="/Jefatura/Documentos/doc/Anexo_5a_Autorizacion.odt">para OpenOffice</a>)</li>
      <li><a href="/Jefatura/Documentos/doc/Anexo6.doc">Anexo 6: Seguimiento de la
            inserci&oacute;n laboral</a></li>
      <li><a href="/Jefatura/Documentos/doc/RelacionAlumnos.doc">Formulario 1: Relaci&oacute;n de alumnos,
         en formato Word</a></li>
      <li><a href="/Jefatura/Documentos/doc/Formulario2.doc">
         Formulario 2: Tramitaci&oacute;n de incidencias
         con Secretar&iacute;a, en formato Word</a></li>
 
    </ul>

    <h4> <a name="fct">Anexos FCT para Erasmus</a></h4>

    <ul style="list-style-image:url(imagenes/ok.png);">

      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexo_1.doc">Anexo 1: Informe visita tutor (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexo_2.doc">Anexo 2: Relación de alumnos (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexo_3.doc">Anexo 3: Programa formativo general (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexos_3_PrFormativo/ProgramaFormativoASIR.doc">
             Anexo 3: Programa formativo para ASIR (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexos_3_PrFormativo/ProgramaFormativoFRIO.doc">
             Anexo 3: Programa formativo para FRIO (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexo_4.doc">Anexo 4: Parte semanal de actividades del alumno (doc)</a></li>
      <li><a href="/Jefatura/Documentos/doc/Erasmus/Anexo_5.doc">Anexo 5: Informe del tutor de la empresa (doc)</a></li>
 
    </ul>

  </div>

</div>

