<?php

  echo "<div id='cuerpo-centro'>
          <h1>MEMBERS ADMINISTRATION</h1>";
 
  
  echo 
        '<ul class="mi-menu2">
            <li><a href="index.php?ampsocges">Start</a></li>
            <li><a href="index.php?ampsocgesalta">New Member</a></li>
            <li><a href="index.php?ampsocgesbusqueda">Search Member</a></li>
            <li><a href="index.php?ampsocgespagar">Pay Fee</a></li>
            <li><a href="index.php?opcion=logout">Exit</a></li>
        </ul>';
  echo 
    '<div id="content">
       <br/><br/>
       <p id="AmpaTitulo">WELCOME TO<br/><br/>MEMBERS ADMINISTRATION</p>
       <br/>
       <img width="500" src="Comun/imagenes/ampa/lampa.png">
     </div>';
 
  echo "</div>";

  
?>
