<?php

  echo "<div id='cuerpo-centro'>
          <h1>GESTIONAR SOCIOS</h1>";
 
  
  echo 
        '<ul class="mi-menu2">
            <li><a href="index.php?ampsocges">Inicio</a></li>
            <li><a href="index.php?ampsocgesalta">Alta Socio</a></li>
            <li><a href="index.php?ampsocgesbusqueda">Buscar Socio</a></li>
            <li><a href="index.php?ampsocgespagar">Pagar Cuota</a></li>
            <li><a href="index.php?opcion=logout">Salir</a></li>
        </ul>';
  echo 
    '<div id="content">
       <br/><br/>
       <p id="AmpaTitulo">BIENVENIDO A LA <br/><br/>GESTION DE SOCIOS DEL AMPA</p>
       <br/>
       <img width="500" src="Comun/imagenes/ampa/lampa.png">
     </div>';
 
  echo "</div>";

  
?>
