<?php
echo "
<div id='cuerpo-centro'>
<h1>CONDITIONS OF USE</h1>
 <p style='text-align:justify'>Technological equipment for general use. Terms of use

Our Institute has different classrooms, facilities, mobile equipment, etc. that allow the use of new technologies in order to prepare and give our lessons. In addition to the specific classrooms belonging to the different departments, there is some equipment that can be used by all teachers and students:

<br>-	Computer Lab (Building C), equipped with 17 computers.
<br>-	Assembly Hall, equipped with a projector and sound system.
<br>-	Three classrooms equipped with an interactive touch screen.
<br>-	Four mobile units with television and DVD player.
<br>-	Two laptops.<br>

In order to use this equipment, please follow the Terms of use that ensure its proper functioning (click here to see more).  <a href='Tic/Condiciones/Condiciones.pdf'>here</a>.<br>
</p>
</div>
"
?>