<?php
echo "
<div id='cuerpo-centro'>
<h1>Condiciones de uso</h1>
 <p style='text-align:justify'>EQUIPACIONES TECNOL&Oacute;GICAS DE USO GENERAL. Normas de uso<br><br> 

	Nuestro Centro dispone de diferentes aulas, instalaciones, equipos m&oacute;viles, etc.<br> 
	que permiten el uso de nuevas tecnolog&iacute;as para preparar e impartir nuestras clases. <br>
	Adem&aacute;s de las aulas espec&iacute;ficas de los diferentes departamentos, existen una serie de equipaciones que pueden ser utilizados por todos los profesores y alumnos:<br><br>

-Aula de inform&aacute;tica del edificio C, dotada de 17 ordenadores.<br>
-Sal&oacute;n de actos, dotado con proyector y equipo de sonido.<br>
-Tres aulas dotadas con pantalla digital interactiva.<br>
-Cuatro equipos m&oacute;viles con televisor y DVD.<br>
-Dos ordenadores port&aacute;tiles.<br><br>

	Para poder utilizar estos elementos hay que seguir unas m&iacute;nimas normas de uso y reserva que garanticen su correcto funcionamiento que se muestra haciendo click <a href='Tic/Condiciones/Condiciones.pdf'>aqui</a>.<br>
</p>
</div>
"
?>